const cfg=window.APP_CONFIG||{};
const state={entries:[],person:'all',range:7,month:new Date(new Date().getFullYear(),new Date().getMonth(),1),familyToken:localStorage.getItem('bp_family_token')||'',demo:!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
const localDT=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
const dateKey=v=>{const d=new Date(v);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const avg=(arr,k)=>arr.length?Math.round(arr.reduce((s,x)=>s+Number(x[k]),0)/arr.length):null;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const seed=()=>{const now=new Date();return Array.from({length:10},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-i);d.setHours(i%2?20:8,15+i);return {id:uid(),person:i%3===0?'Wenqi':'Yihao',systolic:116+(i%4)*3,diastolic:74+(i%3)*2,pulse:62+(i%5)*2,measured_at:d.toISOString(),note:i===2?'散步后测量':''}})};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
async function tokenHash(secret){const data=new TextEncoder().encode(secret);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function api(path,options={}){const headers={'apikey':cfg.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json','x-household-token':state.familyToken,...(options.headers||{})};const r=await fetch(`${cfg.SUPABASE_URL}/rest/v1/${path}`,{...options,headers});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||`HTTP ${r.status}`);return r.status===204?null:r.json()}
async function load(){if(state.demo){state.entries=JSON.parse(localStorage.getItem('bp_entries')||'null')||seed();saveLocal();render();return}if(!state.familyToken){$('#settingsDialog').showModal();return}try{state.entries=await api('blood_pressure_entries?select=*&order=measured_at.desc');setSync(true);render()}catch(e){setSync(false);toast(`同步失败：${e.message}`)}}
function saveLocal(){localStorage.setItem('bp_entries',JSON.stringify(state.entries))}
function setSync(ok){const el=$('#syncState');el.textContent=ok?'云端已同步':state.demo?'本地演示':'同步异常';el.classList.toggle('live',ok)}
async function persist(entry,isDelete=false){if(state.demo){if(isDelete)state.entries=state.entries.filter(x=>x.id!==entry.id);else{const i=state.entries.findIndex(x=>x.id===entry.id);i<0?state.entries.unshift(entry):state.entries.splice(i,1,entry)}saveLocal();render();return}entry={...entry,household_token:state.familyToken};if(isDelete)await api(`blood_pressure_entries?id=eq.${entry.id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});else if(state.entries.some(x=>x.id===entry.id))await api(`blood_pressure_entries?id=eq.${entry.id}`,{method:'PATCH',body:JSON.stringify(entry),headers:{Prefer:'return=representation'}});else await api('blood_pressure_entries',{method:'POST',body:JSON.stringify(entry),headers:{Prefer:'return=representation'}});await load()}
function filtered(){return state.person==='all'?state.entries:state.entries.filter(x=>x.person===state.person)}
function render(){renderSummary();renderChart();renderCalendar();setSync(!state.demo&&!!state.familyToken)}
function renderSummary(){const since=new Date();since.setDate(since.getDate()-state.range+1);since.setHours(0,0,0,0);const rows=filtered().filter(x=>new Date(x.measured_at)>=since);const cards=[['平均高压',avg(rows,'systolic'),'mmHg'],['平均低压',avg(rows,'diastolic'),'mmHg'],['平均心率',avg(rows,'pulse'),'bpm'],['测量次数',rows.length,`${state.range} 天内`]];$('#summaryCards').innerHTML=cards.map(([l,v,u])=>`<article class="metric"><div class="label">${l}</div><div class="value">${v??'—'}</div><div class="unit">${u}</div></article>`).join('')}
function dailySeries(){const start=new Date();start.setDate(start.getDate()-state.range+1);start.setHours(0,0,0,0);const groups={};filtered().filter(x=>new Date(x.measured_at)>=start).forEach(x=>(groups[dateKey(x.measured_at)]??=[]).push(x));return Array.from({length:state.range},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),r=groups[key]||[];return {date:key,label:`${d.getMonth()+1}/${d.getDate()}`,systolic:avg(r,'systolic'),diastolic:avg(r,'diastolic'),pulse:avg(r,'pulse')}})}
function renderChart(){const data=dailySeries(),valid=data.filter(x=>x.systolic!==null),el=$('#trendChart');if(valid.length<2){el.innerHTML='<div class="empty">至少记录两个不同日期后显示趋势</div>';return}const W=900,H=250,p={l:38,r:15,t:15,b:28},min=40,max=180;const x=i=>p.l+i*(W-p.l-p.r)/(data.length-1),y=v=>p.t+(max-v)*(H-p.t-p.b)/(max-min);const path=k=>{let s='',open=false;data.forEach((d,i)=>{if(d[k]==null){open=false;return}s+=`${open?'L':'M'}${x(i).toFixed(1)},${y(d[k]).toFixed(1)} `;open=true});return s};const grids=[60,90,120,150,180].map(v=>`<line class="gridline" x1="${p.l}" y1="${y(v)}" x2="${W-p.r}" y2="${y(v)}"/><text class="axis-label" x="0" y="${y(v)+3}">${v}</text>`).join('');const labels=data.map((d,i)=>i%(state.range===30?5:1)===0?`<text class="axis-label" text-anchor="middle" x="${x(i)}" y="${H-5}">${d.label}</text>`:'').join('');const dots=(k,c)=>data.map((d,i)=>d[k]==null?'':`<circle class="dot" cx="${x(i)}" cy="${y(d[k])}" r="3.5" fill="${c}"><title>${d.date} · ${d[k]}</title></circle>`).join('');el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grids}${labels}<path class="line-sys" d="${path('systolic')}"/><path class="line-dia" d="${path('diastolic')}"/><path class="line-pulse" d="${path('pulse')}"/>${dots('systolic','#3976dd')}${dots('diastolic','#ba8331')}${dots('pulse','#b35e73')}</svg>`}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$('#monthTitle').textContent=`${y} 年 ${m+1} 月`;const first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate();const groups={};filtered().forEach(x=>(groups[dateKey(x.measured_at)]??=[]).push(x));let html='';for(let i=0;i<42;i++){let d,inside=true;if(i<first){d=new Date(y,m-1,prevDays-first+i+1);inside=false}else if(i>=first+days){d=new Date(y,m+1,i-first-days+1);inside=false}else d=new Date(y,m,i-first+1);const key=dateKey(d),rows=groups[key]||[],today=key===dateKey(new Date());const persons=['Yihao','Wenqi'].map(person=>{const r=rows.filter(x=>x.person===person);return r.length?`<div class="avg ${person==='Wenqi'?'wenqi':''}"><strong>${avg(r,'systolic')}/${avg(r,'diastolic')}</strong><small>${person} · ${r.length}次</small></div>`:''}).join('');html+=`<div class="day ${inside?'':'outside'} ${today?'today':''}" data-date="${key}"><span class="day-num">${d.getDate()}</span>${persons}</div>`}$('#calendar').innerHTML=html}
function openEntry(entry=null,date=null){$('#entryForm').reset();$('#entryId').value=entry?.id||'';$('#entryTitle').textContent=entry?'编辑测量':'新增测量';$('#person').value=entry?.person||(state.person==='all'?'Yihao':state.person);$('#systolic').value=entry?.systolic||'';$('#diastolic').value=entry?.diastolic||'';$('#pulse').value=entry?.pulse||'';$('#note').value=entry?.note||'';const d=entry?new Date(entry.measured_at):(date?new Date(`${date}T08:00`):new Date());$('#measuredAt').value=localDT(d);$('#deleteEntry').classList.toggle('hidden',!entry);$('#entryDialog').showModal()}
function openDay(key){const rows=filtered().filter(x=>dateKey(x.measured_at)===key).sort((a,b)=>new Date(a.measured_at)-new Date(b.measured_at));if(!rows.length){openEntry(null,key);return}$('#dayTitle').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date(`${key}T12:00`));$('#daySummary').innerHTML=`<div class="daily-summary"><span>平均高压 <b>${avg(rows,'systolic')}</b></span><span>平均低压 <b>${avg(rows,'diastolic')}</b></span><span>平均心率 <b>${avg(rows,'pulse')}</b></span><span>共 <b>${rows.length}</b> 次</span></div>`;$('#dayEntries').innerHTML=rows.map(x=>`<div class="entry-row" data-id="${x.id}"><div class="time">${new Date(x.measured_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</div><div><div class="reading">${x.systolic} / ${x.diastolic} <small>· ♥ ${x.pulse}</small></div><div class="meta">${x.note||'无备注'}</div></div><span class="person">${x.person}</span></div>`).join('');$('#dayDialog').showModal()}
$$('.close-btn').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('#openEntry').onclick=()=>openEntry();$('#openSettings').onclick=()=>{$('#familyKey').value='';$('#settingsDialog').showModal()};
$('#personFilter').onclick=e=>{if(!e.target.dataset.person)return;state.person=e.target.dataset.person;$$('#personFilter button').forEach(b=>b.classList.toggle('active',b===e.target));render()};$('#rangeFilter').onclick=e=>{if(!e.target.dataset.range)return;state.range=Number(e.target.dataset.range);$$('#rangeFilter button').forEach(b=>b.classList.toggle('active',b===e.target));render()};
$('#prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};$('#calendar').onclick=e=>{const day=e.target.closest('.day');if(day)openDay(day.dataset.date)};$('#dayEntries').onclick=e=>{const row=e.target.closest('.entry-row');if(!row)return;$('#dayDialog').close();openEntry(state.entries.find(x=>x.id===row.dataset.id))};
$('#entryForm').onsubmit=async e=>{e.preventDefault();const old=state.entries.find(x=>x.id===$('#entryId').value);const entry={id:old?.id||uid(),person:$('#person').value,systolic:Number($('#systolic').value),diastolic:Number($('#diastolic').value),pulse:Number($('#pulse').value),measured_at:new Date($('#measuredAt').value).toISOString(),note:$('#note').value.trim(),created_at:old?.created_at||new Date().toISOString()};try{await persist(entry);$('#entryDialog').close();toast('记录已保存')}catch(err){toast(`保存失败：${err.message}`)}};
$('#deleteEntry').onclick=async()=>{const entry=state.entries.find(x=>x.id===$('#entryId').value);if(entry&&confirm('确定删除这条记录吗？')){try{await persist(entry,true);$('#entryDialog').close();toast('记录已删除')}catch(err){toast(`删除失败：${err.message}`)}}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const secret=$('#familyKey').value;if(secret.length<12)return toast('访问密钥至少需要 12 位');state.familyToken=await tokenHash(secret);localStorage.setItem('bp_family_token',state.familyToken);state.demo=false;$('#settingsDialog').close();await load()};$('#useDemo').onclick=()=>{state.demo=true;state.familyToken='';localStorage.removeItem('bp_family_token');$('#settingsDialog').close();load()};
load();
